# Generated by Django 5.0.1 on 2024-01-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
