# Generated by Django 5.0.1 on 2024-01-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/IMG_0151-new.jpg', null=True, upload_to=''),
        ),
    ]
